As a suggestion, rather spend a 404 page than 200.
OXID-eSales/oxideshop_ce pull request #715
Opened 2019-07-16 09:55 UTC by tmloberon

Logically, I'd find it if a controller or function wasn't found. A 404 page comes instead of a 200 Status. Because the route is wrong. Like a Wrong Url.

Triggered by:
- /index.php?cl=non-existent-controller
- /index.php?cl=start&fnc=non-existent-function

2019-07-24 13:14 UTC, Sieg commented
Hi @tmloberon. Double checked how it works - If you have not existing controller situation, you will be redirected to the index page and exception will be logged, and only if your debug mode is on, you will see more information, and i dont see any issues about this workflow. Why you want to change it?

2019-07-24 13:29 UTC, tmloberon commented
A non-existent controller is a non-existent page. We had a module that displayed its own page. We removed the module. The page no longer exists. Thus a 404 status. However Google still crawls over this link and it would be good if a status 404 comes instead of 200.

2019-07-24 17:40 UTC, keywan-ghadami-oxid commented
my 2 cents on this
- this relates to my bug report https://bugs.oxid-esales.com/view.php?id=6370 . Using 404 makes the shop better from my point of view. the 404 page can offer a link to the start page or display products and more so the customer feels not lost. a simple redirect to startpage is just too confusing.
- handleRoutingException must be renamed or somehow changed if there is no exception used anymore

2019-07-26 08:47 UTC, tmloberon commented
If this idea comes to approval. I like to program tests for it.

2019-08-26 13:10 UTC, tabsl commented
+1 ... had a lot of exception spam like

`https://shop/category/product.html?cnid=a849897fd79efe4e86b24e9662a31742&listtype=list&fnc=showLogin`

--> redirect to startpage :-(

2019-08-28 07:50 UTC, jkrug commented
+1

2019-09-10 19:25 UTC, flow-control commented
+1

2020-05-08 13:52 UTC, flow-control commented
Hey @tmloberon :vulcan_salute:

thank you very much for your pull request :+1: 
I talked with PO and we decided, that we want this feature, could you please fix travis and make it :green_heart:?

Thanks in advance

Flo

2021-03-17 12:36 UTC, TumTum commented
Hi @flow-control, I am very happy that this idea was accepted. Have now finally written the tests. By corona I had forgotten that this PR was still open.

2021-03-18 10:32 UTC, flow-control requested changes

2021-03-18 10:44 UTC, tmloberon commented on source/Core/ShopControl.php
> +            }
Yes sure, is also marked that the function should be deleted. As soon the controllers are no longer used by the Metadata v1. Now the question is, should the pull request for v6.2x also merged?

2021-03-18 11:20 UTC, flow-control commented on source/Core/ShopControl.php
> +            }
Currently it targets `master`, @Sieg and I can double check with the team. I'll ping you

2021-08-24 12:26 UTC, TumTum commented
Hi @Sieg I have now updated the code and implemented what @flow-control  said.

2022-03-11 14:53 UTC, Sieg commented
Hey guys, did some changes here, to handle the routing problems in one place, what do you think?

2022-05-06 13:08 UTC, Sieg commented
Merged to master with some changes/improvements (https://github.com/OXID-eSales/oxideshop_ce/compare/85a2dd03e0136c21b1af04b63b5e0de5000b9184...71639371c6b21cd48ffe6169ace52ad3825cd9f4) Thanks.

2022-05-06 13:08 UTC, closed without merging

2022-05-06 13:17 UTC, realFlowControl commented
@Sieg WHOOP WHOOP :tada: